-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 10:54:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL,
  `codigoCurso` INT(4) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cargaHoraria` SMALLINT(0) NULL DEFAULT 3600,
  PRIMARY KEY (`idcursos`),
  UNIQUE INDEX `codigoCurso_UNIQUE` (`codigoCurso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `idmaterias` INT NOT NULL,
  `codigoMateria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargaHoraria` SMALLINT NOT NULL DEFAULT 40,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `iddisciplina` INT NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  `codigoDisciplina` SMALLINT NOT NULL,
  `Vagas` SMALLINT NULL DEFAULT 60,
  `disciplinacol` VARCHAR(45) NULL,
  PRIMARY KEY (`iddisciplina`),
  INDEX `fk_disciplina_materias1_idx` (`materias_idmaterias` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `mydb`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `idalunos` INT NOT NULL,
  `Matricula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`idalunos`),
  INDEX `fk_alunos_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_materias` (
  `cursos_idcursos` INT NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  PRIMARY KEY (`cursos_idcursos`, `materias_idmaterias`),
  INDEX `fk_cursos_has_materias_materias1_idx` (`materias_idmaterias` ASC) VISIBLE,
  INDEX `fk_cursos_has_materias_cursos_idx` (`cursos_idcursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_materias_cursos`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_materias_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `mydb`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails` (
  `idemails` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `alunos_idalunos` INT NOT NULL,
  PRIMARY KEY (`idemails`),
  INDEX `fk_emails_alunos1_idx` (`alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_emails_alunos1`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `mydb`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
